if FUZZER

noinst_PROGRAMS += fuzzer/bluez_pattern_match_fuzzer

fuzzer_bluez_pattern_match_fuzzer_SOURCES = fuzzer/bluez_pattern_match_fuzzer.cc

fuzzer_bluez_pattern_match_fuzzer_CXXFLAGS = -fsanitize=fuzzer-no-link

fuzzer_bluez_pattern_match_fuzzer_LDADD = lib/libbluetooth-internal.la \
					  src/libshared-glib.la -lglib-2.0

fuzzer_bluez_pattern_match_fuzzer_LDFLAGS = -fsanitize=fuzzer


noinst_PROGRAMS += fuzzer/bluez_pattern_new_fuzzer

fuzzer_bluez_pattern_new_fuzzer_SOURCES = fuzzer/bluez_pattern_new_fuzzer.cc

fuzzer_bluez_pattern_new_fuzzer_CXXFLAGS = -fsanitize=fuzzer-no-link

fuzzer_bluez_pattern_new_fuzzer_LDADD = lib/libbluetooth-internal.la \
					src/libshared-glib.la -lglib-2.0

fuzzer_bluez_pattern_new_fuzzer_LDFLAGS = -fsanitize=fuzzer

endif
